name: codec-dev
channels:
  - conda-forge 
dependencies:
  - python=3.12
  - numpy=2.*
  - pytest
  - reedsolo=1.7.*
  - pip=24.*
  - sphinx=7.*
  - sphinx_rtd_theme
  - biopython
  - pip:
    - galois==0.4.*

